POST http://localhost:3003/api/users
Content-Type: application/json

{
  "email": "eaparra@utn.edu.ec",
  "ci": "1006831947",
  "name": "EMILIANO ANDRES PARRA RIVERA",
  "password": "123Em",
  "role": "docente"
}